name: health-ml-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - pandas
      - scikit-learn
      - mlflow
      - xgboost
      - prometheus_client     
      - fastapi
