name: Train ML model using MLflow Project

on:
  push:
    paths:
      - 'ML-Project/**'
      - '.github/workflows/**'

jobs:
  build-and-train:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas

      - name: Run MLflow project
        working-directory: ML-Project
        run: |
          mlflow run . -b local --no-conda -P data_path=healthcare_preprocessed.csv