name: health-detection

entry_points:
  main:
    parameters:
      data_path: {type: str}
    command: "python modelling.py --data_path {data_path}"

jobs:
  build-and-train:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade mlflow
          pip install scikit-learn pandas

      - name: Run MLflow project
        run: |
          cd ML-Project
          python -m mlflow run . -b local -P data_path=healthcare_preprocessed.csv