name: Train ML model using MLflow Project

on:
  push:
    paths:
      - 'ML-Project/**'
      - '.github/workflows/**'

jobs:
  build-and-train:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade mlflow
          pip install scikit-learn pandas

      - name: Run MLflow project
        run: |
          cd ML-Project
          mlflow run . -b local -P data_path=healthcare_preprocessed.csv